spring:
  application:
    name: jooq

  datasource:
    url: jdbc:mysql://localhost:13306/sakila?allowMultiQueries=true
    username: root
    password: passwd
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG


